language: python

python: 3.5

sudo: required

services:
    - mongodb
    - elasticsearch
    - redis-server

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - sudo apt-get install g++-4.8 --allow-unauthenticated
    - export CXX="g++-4.8" CC="gcc-4.8"
    - $CXX --version
    - nvm install node
    - nvm use node
    - node --version
    - rm -f .npm/*.lock
    - npm install -g npm@latest
    - npm config set loglevel warn
node_js:
    - '6'
install:
    - npm install
    - cd server && pip install -q -r requirements.txt && cd ..
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
script:
    - make test
