language: python

python: 3.5

dist: trusty
sudo: required

services:
    - mongodb
    - redis-server

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    - elasticsearch-2.x
    packages:
    - mongodb-org-server
    - elasticsearch

cache:
    - pip
    - npm

before_install:
    - npm config set loglevel warn
    - sudo apt-get purge elasticsearch
    - sudo apt-get install -t stable elasticsearch
    - sudo service elasticsearch restart

install:
    - npm install
    - cd server && pip install -q -r requirements.txt && cd ..
    - chmod a+x server/scripts/install-highcharts-export-server.sh
    - cd server/scripts && ./install-highcharts-export-server.sh && cd ../../

script:
    - cd server && python3 -u -m analytics.reports.highcharts_server &
    - make test
