language: python

python: 3.5

dist: trusty
sudo: required

services:
    - docker

env:
  global:
    - TRAVIS_NODE_VERSION="6"

cache:
    - pip
    - npm

before_install:
    - docker-compose pull
    - node --version
    - docker-compose up -d

install:
    - npm install
    - cd server && pip install -r requirements.txt && cd ..
    - chmod a+x server/scripts/install-highcharts-export-server.sh
    - pip install -e .

script:
    - cd server && python3 -u -m analytics.reports.highcharts_server &
    - make testpy
    - make testjs

after_success:
    - coveralls
